---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Samba-related packages are installed (RedHat).
  ansible.builtin.package:
    name:
      - samba
      - samba-client
      - samba-common
      - cifs-utils
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure Samba-related packages are installed (Debian).
  ansible.builtin.apt:
    name:
      - samba
      - samba-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure Samba is running and set to start on boot.
  ansible.builtin.service:
    name: "{{ samba_daemon }}"
    state: started
    enabled: true
